services:
  - type: web
    name: talentlens-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://talentlenssolutions_db_user:TalentLens008@talentlens.xohr8ul.mongodb.net/talentlens?retryWrites=true&w=majority&appName=TalentLens
      - key: DB_NAME
        value: talentlens
      - key: CORS_ORIGINS
        value: "*"
      - key: MAIL_USERNAME
        value: talentlens.solutions@gmail.com
      - key: MAIL_PASSWORD
        value: xxeqhxzzctfyvjol
      - key: MAIL_FROM
        value: talentlens.solutions@gmail.com
      - key: MAIL_FROM_NAME
        value: TalentLens Solutions
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: PYTHON_VERSION
        value: "3.11.0"
